### ISSUE TITLE
pytest

### ISSUE THREAD

**Issue by NikomSol** [NikomSol/Anritsu-Network-Analyzer#1]
Я научился переписывать путь pytest, теперь он может воспринимать библиотеки из основной директории, но теперь!
При запуске через pytest не находит стандартную библиотеку serial 

tests\test_myserial.py:3: in <module>
    from myserial import Serial
myserial.py:1: in <module>
    import serial
E   ModuleNotFoundError: No module named 'serial'

**Comment by VulpesCorsac** [comment]
1) сделай 
pip freeze > requirements.txt
потому что не очень понятно, что у тебя вообще стоит, например, esptool вот не очень был очевиден
2) после небольшого шаманства, у меня тест взлетает (ну, как, у меня нет портов, поэтому он, конечно, разваливается, но всё равно работает), так что надо думать, пока у меня нет идей.
3) если ты используешь pytets (например, pytest.raises), то укажи его в импорте файла. Ну и про две пустые строки между функциями тоже не забывай, даже в тестовом файле
4) PYTHONPATH = "D:\Work\Programming\Anritsu Network Analyzer" . Ну, как бы, ты можешь получить с помощью pathlib текущую директорию, а уже потом от неё через parent() ходить куда нужно, получится относительный путь и это намного удобнее

**Comment by NikomSol** [comment]
В общем, что-то из этого помогло:
Либо pip freeze > requirements.txt
Либо pip install pytest

**Comment by VulpesCorsac** [comment]
pip freeze > requirements.txt
просто выгружает состояние библиотек пайтона, чтобы можно было посмотреть, что у тебя установлено, каких версий и т.д.

pip install pytest
собственно, ставит сам pytest, было бы странно пытаться его использоваться, не установив.

Всё работает? Если да, то можешь закрыть issue

**Comment by VulpesCorsac** [comment]
Кстати, этот самый requirements ты бы тоже заливал в репу, так будет понятнее, как поднять её локально у себя

**Comment by NikomSol** [comment]
Но pytest частично работал, даже когда не стоял, он же не ругался, что не знает что я от него хочу, он ругался что не может найти serial
Может конечно, это что-то типо базовой комплектации... но кто знает
